name: xinlian-OA-app CI

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Build
      - uses: bowerchen/xinlian-OA-app@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}